Non-root user for HA under s6-overlay
This actually replaces the Home Assistant run script with the whole user
check, package install and venv management deals. Using S6 this would
be preferable to add these things to /etc/cont-init.d/.

The current solution is mostly for simplicity and easier end-user setups.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,22 +1,67 @@
-#!/bin/sh
+#!/usr/bin/with-contenv bashio
 
-set -e
+USER="homeassistant"
+PUID="${PUID:-1000}"
+PGID="${PGID:-1000}"
 
-VENV="${VENV:-/var/tmp/venv}"
-log(){ echo "$*" >&2; }
+UMASK="${UMASK:-}"
 
-log "Running as $(id -u):$(id -g)"
+PACKAGES="${PACKAGES:-}"
 
-if [ -n "$UMASK" ]; then
-  log "Setting umask to $UMASK"
+VENV_PATH="${VENV:-/var/tmp/homeassistant-venv}"
+CONFIG_PATH=/config
+
+#
+# Creating user
+#
+
+# Some HA commands seem to fail if we don't have an actual user.
+# ie: shell_command would return error code 255
+bashio::log.info "Creating user $USER with $PUID:$PGID"
+
+deluser "$USER" >/dev/null 2>&1 || true
+delgroup "$USER" >/dev/null 2>&1 || true
+
+addgroup -g "$PGID" "$USER"
+adduser -G "$USER" -D -H -u "$PUID" "$USER"
+
+#
+# Install extra packages
+#
+
+if [ -n "${PACKAGES}" ]; then
+  bashio::log.info "Installing extra packages: $PACKAGES"
+  apk add --quiet --no-progress --no-cache $PACKAGES
+fi
+
+#
+# Create virtual environment
+#
+
+bashio::log.info "Initializing venv in $VENV_PATH"
+su "$USER" \
+  -c "python3 -m venv --system-site-packages '$VENV_PATH'"
+
+#
+# Fix permissions
+#
+
+cd "$CONFIG_PATH" || bashio::exit.nok "Can't find config folder: $CONFIG_PATH"
+chown -R "$USER:$USER" .
+
+if [ -n "${UMASK}" ]; then
+  bashio::log.info "Setting umask: $UMASK"
   umask "$UMASK"
 fi
 
-log "Initializing venv in $VENV"
-python3 -m venv --system-site-packages "$VENV"
-. "$VENV/bin/activate"
+#
+# Run homeassistant
+#
 
-log "Starting homeassistant"
-set -- ${@:-python3 -m homeassistant --config /config}
-# replace the current pid 1 with the original command
-exec "$@"
+bashio::log.info "Activating venv"
+. "$VENV_PATH/bin/activate"
+
+bashio::log.info "Starting homeassistant"
+exec \
+  s6-setuidgid "$USER" \
+  python3 -m homeassistant --config "$CONFIG_PATH"
